<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="9" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="88" started-at="2015-02-08T22:33:44Z" finished-at="2015-02-08T22:33:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="88" started-at="2015-02-08T22:33:44Z" finished-at="2015-02-08T22:33:44Z">
      <class name="rps.NewTest">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:rps.NewTest@6956de9]" name="setUpClass" is-config="true" duration-ms="21" started-at="2015-02-08T23:33:44Z" finished-at="2015-02-08T23:33:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="PASS" signature="testLostPlay(rps.RPSEnum, rps.RPSEnum)[pri:0, instance:rps.NewTest@6956de9]" name="testLostPlay" duration-ms="9" started-at="2015-02-08T23:33:44Z" data-provider="Lost" finished-at="2015-02-08T23:33:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ROCK]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PAPER]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLostPlay -->
        <test-method status="PASS" signature="testLostPlay(rps.RPSEnum, rps.RPSEnum)[pri:0, instance:rps.NewTest@6956de9]" name="testLostPlay" duration-ms="1" started-at="2015-02-08T23:33:44Z" data-provider="Lost" finished-at="2015-02-08T23:33:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PAPER]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[SCISORS]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLostPlay -->
        <test-method status="PASS" signature="testLostPlay(rps.RPSEnum, rps.RPSEnum)[pri:0, instance:rps.NewTest@6956de9]" name="testLostPlay" duration-ms="1" started-at="2015-02-08T23:33:44Z" data-provider="Lost" finished-at="2015-02-08T23:33:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[SCISORS]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ROCK]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLostPlay -->
        <test-method status="PASS" signature="testTiePlay(rps.RPSEnum, rps.RPSEnum)[pri:0, instance:rps.NewTest@6956de9]" name="testTiePlay" duration-ms="1" started-at="2015-02-08T23:33:44Z" data-provider="Tie" finished-at="2015-02-08T23:33:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ROCK]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ROCK]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTiePlay -->
        <test-method status="PASS" signature="testTiePlay(rps.RPSEnum, rps.RPSEnum)[pri:0, instance:rps.NewTest@6956de9]" name="testTiePlay" duration-ms="1" started-at="2015-02-08T23:33:44Z" data-provider="Tie" finished-at="2015-02-08T23:33:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PAPER]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PAPER]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTiePlay -->
        <test-method status="PASS" signature="testTiePlay(rps.RPSEnum, rps.RPSEnum)[pri:0, instance:rps.NewTest@6956de9]" name="testTiePlay" duration-ms="2" started-at="2015-02-08T23:33:44Z" data-provider="Tie" finished-at="2015-02-08T23:33:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[SCISORS]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[SCISORS]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTiePlay -->
        <test-method status="FAIL" signature="testWinPlay(rps.RPSEnum, rps.RPSEnum)[pri:0, instance:rps.NewTest@6956de9]" name="testWinPlay" duration-ms="3" started-at="2015-02-08T23:33:44Z" data-provider="Win" finished-at="2015-02-08T23:33:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ROCK]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[SCISORS]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [WIN] but found [TIE]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [WIN] but found [TIE]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at rps.NewTest.testWinPlay(NewTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWinPlay -->
        <test-method status="FAIL" signature="testWinPlay(rps.RPSEnum, rps.RPSEnum)[pri:0, instance:rps.NewTest@6956de9]" name="testWinPlay" duration-ms="2" started-at="2015-02-08T23:33:44Z" data-provider="Win" finished-at="2015-02-08T23:33:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PAPER]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ROCK]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [WIN] but found [TIE]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [WIN] but found [TIE]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at rps.NewTest.testWinPlay(NewTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWinPlay -->
        <test-method status="FAIL" signature="testWinPlay(rps.RPSEnum, rps.RPSEnum)[pri:0, instance:rps.NewTest@6956de9]" name="testWinPlay" duration-ms="1" started-at="2015-02-08T23:33:44Z" data-provider="Win" finished-at="2015-02-08T23:33:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[SCISORS]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PAPER]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [WIN] but found [TIE]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [WIN] but found [TIE]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at rps.NewTest.testWinPlay(NewTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWinPlay -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:rps.NewTest@6956de9]" name="tearDownClass" is-config="true" duration-ms="0" started-at="2015-02-08T23:33:44Z" finished-at="2015-02-08T23:33:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- rps.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
